USE [master]
GO
/****** Object:  Database [FoodSystem]    Script Date: 27-06-2022 21:07:34 ******/
CREATE DATABASE [FoodSystem]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FoodSystem', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\FoodSystem.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'FoodSystem_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\FoodSystem_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [FoodSystem] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FoodSystem].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [FoodSystem] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [FoodSystem] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [FoodSystem] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [FoodSystem] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [FoodSystem] SET ARITHABORT OFF 
GO
ALTER DATABASE [FoodSystem] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [FoodSystem] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [FoodSystem] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [FoodSystem] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [FoodSystem] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [FoodSystem] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [FoodSystem] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [FoodSystem] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [FoodSystem] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [FoodSystem] SET  DISABLE_BROKER 
GO
ALTER DATABASE [FoodSystem] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [FoodSystem] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [FoodSystem] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [FoodSystem] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [FoodSystem] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [FoodSystem] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [FoodSystem] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [FoodSystem] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [FoodSystem] SET  MULTI_USER 
GO
ALTER DATABASE [FoodSystem] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [FoodSystem] SET DB_CHAINING OFF 
GO
ALTER DATABASE [FoodSystem] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [FoodSystem] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [FoodSystem] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [FoodSystem] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [FoodSystem] SET QUERY_STORE = OFF
GO
USE [FoodSystem]
GO
/****** Object:  Table [dbo].[ContactMst]    Script Date: 27-06-2022 21:07:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ContactMst](
	[FullName] [nvarchar](256) NOT NULL,
	[Email] [nvarchar](50) NOT NULL,
	[Message] [nvarchar](250) NOT NULL,
 CONSTRAINT [PK_ContactMst] PRIMARY KEY CLUSTERED 
(
	[FullName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[OrderMst]    Script Date: 27-06-2022 21:07:35 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[OrderMst](
	[OID] [int] IDENTITY(1,1) NOT NULL,
	[Email] [nvarchar](50) NULL,
	[PName] [nvarchar](50) NULL,
	[Price] [float] NULL,
	[Qnt] [int] NULL,
	[TotalPrice] [float] NULL,
	[Status] [nvarchar](50) NULL,
 CONSTRAINT [PK_OrderMst] PRIMARY KEY CLUSTERED 
(
	[OID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PaymentMst]    Script Date: 27-06-2022 21:07:35 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PaymentMst](
	[PID] [int] IDENTITY(1,1) NOT NULL,
	[Email] [nvarchar](50) NULL,
	[Type] [nvarchar](50) NULL,
	[BankName] [nvarchar](50) NULL,
	[CardNo] [nvarchar](50) NULL,
	[CVV] [nvarchar](50) NULL,
	[Amount] [float] NULL,
	[UPI] [nvarchar](50) NULL,
	[NAMEONCARD] [nchar](50) NULL,
	[EXPIRY] [nchar](50) NULL,
 CONSTRAINT [PK_PaymentMst] PRIMARY KEY CLUSTERED 
(
	[PID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ProductMst]    Script Date: 27-06-2022 21:07:35 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ProductMst](
	[PID] [int] IDENTITY(1,1) NOT NULL,
	[PName] [nvarchar](50) NULL,
	[Price] [float] NULL,
	[Status] [int] NULL,
	[FoodImage] [varbinary](max) NULL,
	[ImageName] [nvarchar](50) NULL,
 CONSTRAINT [PK_ProductMst] PRIMARY KEY CLUSTERED 
(
	[PID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UserMst]    Script Date: 27-06-2022 21:07:35 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserMst](
	[UID] [int] IDENTITY(1,1) NOT NULL,
	[Fname] [nvarchar](50) NULL,
	[Lname] [nvarchar](50) NULL,
	[Mobile] [nvarchar](50) NULL,
	[Gender] [nvarchar](50) NULL,
	[Address] [nvarchar](50) NULL,
	[City] [nvarchar](50) NULL,
	[Pincode] [nvarchar](50) NULL,
	[Email] [nvarchar](50) NOT NULL,
	[Password] [nvarchar](50) NULL,
 CONSTRAINT [PK_UserMst_1] PRIMARY KEY CLUSTERED 
(
	[Email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [FoodSystem] SET  READ_WRITE 
GO